// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukcuddqdgkouzocjwljl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrY3VkZHFkZ2tvdXpvY2p3bGpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0Mzc1MzAsImV4cCI6MjA3NDAxMzUzMH0.JLLh3U5KeqBYJx6kuz-66gdcsb16ZzmTwgcl4IkKLsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});